<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA5dax4x\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA5dax4x/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA5dax4x.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA5dax4x\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerA5dax4x\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'A5dax4x',
    'container.build_id' => '7d94e297',
    'container.build_time' => 1581522343,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA5dax4x');
