<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSEAooQU\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSEAooQU/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSEAooQU.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSEAooQU\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSEAooQU\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SEAooQU',
    'container.build_id' => '0663ad37',
    'container.build_time' => 1581683872,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSEAooQU');
