<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAe0tToQ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAe0tToQ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAe0tToQ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAe0tToQ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAe0tToQ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Ae0tToQ',
    'container.build_id' => '911847ee',
    'container.build_time' => 1581616263,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAe0tToQ');
